// Code generated by protoc-gen-go. DO NOT EDIT.
// source: movies.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetMoviesResponse struct {
	Movies               []*Movie `protobuf:"bytes,1,rep,name=movies" json:"movies,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMoviesResponse) Reset()         { *m = GetMoviesResponse{} }
func (m *GetMoviesResponse) String() string { return proto.CompactTextString(m) }
func (*GetMoviesResponse) ProtoMessage()    {}
func (*GetMoviesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_movies_5534f4323ae0fd3c, []int{0}
}
func (m *GetMoviesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMoviesResponse.Unmarshal(m, b)
}
func (m *GetMoviesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMoviesResponse.Marshal(b, m, deterministic)
}
func (dst *GetMoviesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMoviesResponse.Merge(dst, src)
}
func (m *GetMoviesResponse) XXX_Size() int {
	return xxx_messageInfo_GetMoviesResponse.Size(m)
}
func (m *GetMoviesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMoviesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMoviesResponse proto.InternalMessageInfo

func (m *GetMoviesResponse) GetMovies() []*Movie {
	if m != nil {
		return m.Movies
	}
	return nil
}

func (m *GetMoviesResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type Movie struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Title                string               `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Director             string               `protobuf:"bytes,3,opt,name=director" json:"director,omitempty"`
	Year                 string               `protobuf:"bytes,4,opt,name=year" json:"year,omitempty"`
	Userid               string               `protobuf:"bytes,5,opt,name=userid" json:"userid,omitempty"`
	Createdon            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=createdon" json:"createdon,omitempty"`
	Updatedon            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=updatedon" json:"updatedon,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Movie) Reset()         { *m = Movie{} }
func (m *Movie) String() string { return proto.CompactTextString(m) }
func (*Movie) ProtoMessage()    {}
func (*Movie) Descriptor() ([]byte, []int) {
	return fileDescriptor_movies_5534f4323ae0fd3c, []int{1}
}
func (m *Movie) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Movie.Unmarshal(m, b)
}
func (m *Movie) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Movie.Marshal(b, m, deterministic)
}
func (dst *Movie) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Movie.Merge(dst, src)
}
func (m *Movie) XXX_Size() int {
	return xxx_messageInfo_Movie.Size(m)
}
func (m *Movie) XXX_DiscardUnknown() {
	xxx_messageInfo_Movie.DiscardUnknown(m)
}

var xxx_messageInfo_Movie proto.InternalMessageInfo

func (m *Movie) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Movie) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Movie) GetDirector() string {
	if m != nil {
		return m.Director
	}
	return ""
}

func (m *Movie) GetYear() string {
	if m != nil {
		return m.Year
	}
	return ""
}

func (m *Movie) GetUserid() string {
	if m != nil {
		return m.Userid
	}
	return ""
}

func (m *Movie) GetCreatedon() *timestamp.Timestamp {
	if m != nil {
		return m.Createdon
	}
	return nil
}

func (m *Movie) GetUpdatedon() *timestamp.Timestamp {
	if m != nil {
		return m.Updatedon
	}
	return nil
}

type GetMovieByIdRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMovieByIdRequest) Reset()         { *m = GetMovieByIdRequest{} }
func (m *GetMovieByIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetMovieByIdRequest) ProtoMessage()    {}
func (*GetMovieByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_movies_5534f4323ae0fd3c, []int{2}
}
func (m *GetMovieByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMovieByIdRequest.Unmarshal(m, b)
}
func (m *GetMovieByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMovieByIdRequest.Marshal(b, m, deterministic)
}
func (dst *GetMovieByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMovieByIdRequest.Merge(dst, src)
}
func (m *GetMovieByIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetMovieByIdRequest.Size(m)
}
func (m *GetMovieByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMovieByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMovieByIdRequest proto.InternalMessageInfo

func (m *GetMovieByIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetMovieByIdResponse struct {
	Movie                *Movie   `protobuf:"bytes,1,opt,name=movie" json:"movie,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMovieByIdResponse) Reset()         { *m = GetMovieByIdResponse{} }
func (m *GetMovieByIdResponse) String() string { return proto.CompactTextString(m) }
func (*GetMovieByIdResponse) ProtoMessage()    {}
func (*GetMovieByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_movies_5534f4323ae0fd3c, []int{3}
}
func (m *GetMovieByIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMovieByIdResponse.Unmarshal(m, b)
}
func (m *GetMovieByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMovieByIdResponse.Marshal(b, m, deterministic)
}
func (dst *GetMovieByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMovieByIdResponse.Merge(dst, src)
}
func (m *GetMovieByIdResponse) XXX_Size() int {
	return xxx_messageInfo_GetMovieByIdResponse.Size(m)
}
func (m *GetMovieByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMovieByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMovieByIdResponse proto.InternalMessageInfo

func (m *GetMovieByIdResponse) GetMovie() *Movie {
	if m != nil {
		return m.Movie
	}
	return nil
}

func (m *GetMovieByIdResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type NewMovieRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Director             string   `protobuf:"bytes,2,opt,name=director" json:"director,omitempty"`
	Year                 string   `protobuf:"bytes,3,opt,name=year" json:"year,omitempty"`
	Userid               string   `protobuf:"bytes,4,opt,name=userid" json:"userid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewMovieRequest) Reset()         { *m = NewMovieRequest{} }
func (m *NewMovieRequest) String() string { return proto.CompactTextString(m) }
func (*NewMovieRequest) ProtoMessage()    {}
func (*NewMovieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_movies_5534f4323ae0fd3c, []int{4}
}
func (m *NewMovieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewMovieRequest.Unmarshal(m, b)
}
func (m *NewMovieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewMovieRequest.Marshal(b, m, deterministic)
}
func (dst *NewMovieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewMovieRequest.Merge(dst, src)
}
func (m *NewMovieRequest) XXX_Size() int {
	return xxx_messageInfo_NewMovieRequest.Size(m)
}
func (m *NewMovieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewMovieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewMovieRequest proto.InternalMessageInfo

func (m *NewMovieRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *NewMovieRequest) GetDirector() string {
	if m != nil {
		return m.Director
	}
	return ""
}

func (m *NewMovieRequest) GetYear() string {
	if m != nil {
		return m.Year
	}
	return ""
}

func (m *NewMovieRequest) GetUserid() string {
	if m != nil {
		return m.Userid
	}
	return ""
}

type NewMovieResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewMovieResponse) Reset()         { *m = NewMovieResponse{} }
func (m *NewMovieResponse) String() string { return proto.CompactTextString(m) }
func (*NewMovieResponse) ProtoMessage()    {}
func (*NewMovieResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_movies_5534f4323ae0fd3c, []int{5}
}
func (m *NewMovieResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewMovieResponse.Unmarshal(m, b)
}
func (m *NewMovieResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewMovieResponse.Marshal(b, m, deterministic)
}
func (dst *NewMovieResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewMovieResponse.Merge(dst, src)
}
func (m *NewMovieResponse) XXX_Size() int {
	return xxx_messageInfo_NewMovieResponse.Size(m)
}
func (m *NewMovieResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewMovieResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewMovieResponse proto.InternalMessageInfo

func (m *NewMovieResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NewMovieResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_movies_5534f4323ae0fd3c, []int{6}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GetMoviesResponse)(nil), "pb.GetMoviesResponse")
	proto.RegisterType((*Movie)(nil), "pb.Movie")
	proto.RegisterType((*GetMovieByIdRequest)(nil), "pb.GetMovieByIdRequest")
	proto.RegisterType((*GetMovieByIdResponse)(nil), "pb.GetMovieByIdResponse")
	proto.RegisterType((*NewMovieRequest)(nil), "pb.NewMovieRequest")
	proto.RegisterType((*NewMovieResponse)(nil), "pb.NewMovieResponse")
	proto.RegisterType((*Empty)(nil), "pb.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Movies service

type MoviesClient interface {
	GetMovies(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetMoviesResponse, error)
	GetMovieById(ctx context.Context, in *GetMovieByIdRequest, opts ...grpc.CallOption) (*GetMovieByIdResponse, error)
	NewMovie(ctx context.Context, in *NewMovieRequest, opts ...grpc.CallOption) (*NewMovieResponse, error)
}

type moviesClient struct {
	cc *grpc.ClientConn
}

func NewMoviesClient(cc *grpc.ClientConn) MoviesClient {
	return &moviesClient{cc}
}

func (c *moviesClient) GetMovies(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetMoviesResponse, error) {
	out := new(GetMoviesResponse)
	err := grpc.Invoke(ctx, "/pb.Movies/GetMovies", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moviesClient) GetMovieById(ctx context.Context, in *GetMovieByIdRequest, opts ...grpc.CallOption) (*GetMovieByIdResponse, error) {
	out := new(GetMovieByIdResponse)
	err := grpc.Invoke(ctx, "/pb.Movies/GetMovieById", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moviesClient) NewMovie(ctx context.Context, in *NewMovieRequest, opts ...grpc.CallOption) (*NewMovieResponse, error) {
	out := new(NewMovieResponse)
	err := grpc.Invoke(ctx, "/pb.Movies/NewMovie", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Movies service

type MoviesServer interface {
	GetMovies(context.Context, *Empty) (*GetMoviesResponse, error)
	GetMovieById(context.Context, *GetMovieByIdRequest) (*GetMovieByIdResponse, error)
	NewMovie(context.Context, *NewMovieRequest) (*NewMovieResponse, error)
}

func RegisterMoviesServer(s *grpc.Server, srv MoviesServer) {
	s.RegisterService(&_Movies_serviceDesc, srv)
}

func _Movies_GetMovies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoviesServer).GetMovies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Movies/GetMovies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoviesServer).GetMovies(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Movies_GetMovieById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMovieByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoviesServer).GetMovieById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Movies/GetMovieById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoviesServer).GetMovieById(ctx, req.(*GetMovieByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Movies_NewMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewMovieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoviesServer).NewMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Movies/NewMovie",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoviesServer).NewMovie(ctx, req.(*NewMovieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Movies_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Movies",
	HandlerType: (*MoviesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMovies",
			Handler:    _Movies_GetMovies_Handler,
		},
		{
			MethodName: "GetMovieById",
			Handler:    _Movies_GetMovieById_Handler,
		},
		{
			MethodName: "NewMovie",
			Handler:    _Movies_NewMovie_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "movies.proto",
}

func init() { proto.RegisterFile("movies.proto", fileDescriptor_movies_5534f4323ae0fd3c) }

var fileDescriptor_movies_5534f4323ae0fd3c = []byte{
	// 389 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcd, 0x6e, 0xe2, 0x30,
	0x10, 0x80, 0x37, 0x09, 0x09, 0x64, 0x40, 0xbb, 0xec, 0xc0, 0xee, 0x5a, 0xb9, 0xc0, 0x46, 0x5a,
	0x89, 0x53, 0x90, 0xd8, 0x4a, 0xed, 0xb9, 0x55, 0xd5, 0x72, 0x68, 0x0f, 0x51, 0x5f, 0x80, 0x90,
	0x29, 0x8a, 0x44, 0x70, 0xea, 0x38, 0xad, 0x78, 0xb2, 0x3e, 0x53, 0xdf, 0xa2, 0x8a, 0xf3, 0x43,
	0xf8, 0x53, 0x6f, 0xf6, 0xcc, 0x37, 0xb6, 0xe7, 0xf3, 0x40, 0x2f, 0xe6, 0xaf, 0x11, 0xa5, 0x5e,
	0x22, 0xb8, 0xe4, 0xa8, 0x27, 0x81, 0x33, 0x5a, 0x71, 0xbe, 0x5a, 0xd3, 0x54, 0x45, 0x82, 0xec,
	0x79, 0x2a, 0xa3, 0x98, 0x52, 0xb9, 0x88, 0x93, 0x02, 0x72, 0xef, 0xe1, 0xe7, 0x1d, 0xc9, 0x07,
	0x55, 0xe7, 0x53, 0x9a, 0xf0, 0x4d, 0x4a, 0xf8, 0x17, 0xac, 0xe2, 0x24, 0xa6, 0x8d, 0x8d, 0x49,
	0x77, 0x66, 0x7b, 0x49, 0xe0, 0x29, 0xc6, 0x2f, 0x13, 0xd8, 0x07, 0x83, 0x84, 0x60, 0xfa, 0x58,
	0x9b, 0xd8, 0x7e, 0xbe, 0x74, 0x3f, 0x34, 0x30, 0x15, 0x83, 0xdf, 0x41, 0x8f, 0x42, 0xa6, 0xa9,
	0x94, 0x1e, 0x85, 0x38, 0x04, 0x53, 0x46, 0x72, 0x4d, 0x25, 0x5d, 0x6c, 0xd0, 0x81, 0x4e, 0x18,
	0x09, 0x5a, 0x4a, 0x2e, 0x98, 0xa1, 0x12, 0xf5, 0x1e, 0x11, 0x5a, 0x5b, 0x5a, 0x08, 0xd6, 0x52,
	0x71, 0xb5, 0xc6, 0xdf, 0x60, 0x65, 0x29, 0x89, 0x28, 0x64, 0xa6, 0x8a, 0x96, 0x3b, 0xbc, 0x02,
	0x7b, 0x29, 0x68, 0x21, 0x29, 0xe4, 0x1b, 0x66, 0x8d, 0xb5, 0x49, 0x77, 0xe6, 0x78, 0x45, 0xdb,
	0x5e, 0xd5, 0xb6, 0xf7, 0x54, 0xb5, 0xed, 0xef, 0xe0, 0xbc, 0x32, 0x4b, 0xc2, 0xb2, 0xb2, 0xfd,
	0x75, 0x65, 0x0d, 0xbb, 0xff, 0x60, 0x50, 0x59, 0xbb, 0xde, 0xce, 0x43, 0x9f, 0x5e, 0x32, 0x4a,
	0xe5, 0x61, 0xe3, 0xee, 0x1c, 0x86, 0xfb, 0x58, 0xe9, 0x77, 0x04, 0xa6, 0xd2, 0xa8, 0xd0, 0x3d,
	0xbd, 0x45, 0xfc, 0x84, 0x5d, 0x0e, 0x3f, 0x1e, 0xe9, 0xad, 0x80, 0xca, 0xdb, 0x6a, 0xad, 0xda,
	0x39, 0xad, 0xfa, 0x19, 0xad, 0xc6, 0x49, 0xad, 0xad, 0xa6, 0x56, 0xf7, 0x02, 0xfa, 0xbb, 0x0b,
	0xcb, 0x77, 0x1f, 0x7e, 0xec, 0xf1, 0x33, 0xdb, 0x60, 0xde, 0xc6, 0x89, 0xdc, 0xce, 0xde, 0x35,
	0xb0, 0x8a, 0xa9, 0xc2, 0x29, 0xd8, 0xf5, 0x88, 0xa1, 0xea, 0x55, 0x21, 0xce, 0xaf, 0x7c, 0x79,
	0x34, 0x7c, 0xee, 0x37, 0xbc, 0x81, 0x5e, 0x53, 0x1b, 0xfe, 0x69, 0x82, 0x0d, 0xdf, 0x0e, 0x3b,
	0x4e, 0xd4, 0x87, 0x5c, 0x42, 0xa7, 0x7a, 0x3f, 0x0e, 0x72, 0xee, 0x40, 0x9f, 0x33, 0xdc, 0x0f,
	0x56, 0x85, 0x81, 0xa5, 0xbe, 0xfe, 0xff, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x54, 0x2d, 0x91,
	0xf6, 0x4d, 0x03, 0x00, 0x00,
}
