// Code generated by protoc-gen-go. DO NOT EDIT.
// source: movies.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetMoviesResponse struct {
	Movies               []*Movie `protobuf:"bytes,1,rep,name=movies" json:"movies,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMoviesResponse) Reset()         { *m = GetMoviesResponse{} }
func (m *GetMoviesResponse) String() string { return proto.CompactTextString(m) }
func (*GetMoviesResponse) ProtoMessage()    {}
func (*GetMoviesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_movies_5e83975f200d6708, []int{0}
}
func (m *GetMoviesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMoviesResponse.Unmarshal(m, b)
}
func (m *GetMoviesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMoviesResponse.Marshal(b, m, deterministic)
}
func (dst *GetMoviesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMoviesResponse.Merge(dst, src)
}
func (m *GetMoviesResponse) XXX_Size() int {
	return xxx_messageInfo_GetMoviesResponse.Size(m)
}
func (m *GetMoviesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMoviesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMoviesResponse proto.InternalMessageInfo

func (m *GetMoviesResponse) GetMovies() []*Movie {
	if m != nil {
		return m.Movies
	}
	return nil
}

func (m *GetMoviesResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type Movie struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Title                string               `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Director             string               `protobuf:"bytes,3,opt,name=director" json:"director,omitempty"`
	Year                 string               `protobuf:"bytes,4,opt,name=year" json:"year,omitempty"`
	Userid               string               `protobuf:"bytes,5,opt,name=userid" json:"userid,omitempty"`
	Createdon            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=createdon" json:"createdon,omitempty"`
	Updatedon            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=updatedon" json:"updatedon,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Movie) Reset()         { *m = Movie{} }
func (m *Movie) String() string { return proto.CompactTextString(m) }
func (*Movie) ProtoMessage()    {}
func (*Movie) Descriptor() ([]byte, []int) {
	return fileDescriptor_movies_5e83975f200d6708, []int{1}
}
func (m *Movie) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Movie.Unmarshal(m, b)
}
func (m *Movie) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Movie.Marshal(b, m, deterministic)
}
func (dst *Movie) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Movie.Merge(dst, src)
}
func (m *Movie) XXX_Size() int {
	return xxx_messageInfo_Movie.Size(m)
}
func (m *Movie) XXX_DiscardUnknown() {
	xxx_messageInfo_Movie.DiscardUnknown(m)
}

var xxx_messageInfo_Movie proto.InternalMessageInfo

func (m *Movie) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Movie) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Movie) GetDirector() string {
	if m != nil {
		return m.Director
	}
	return ""
}

func (m *Movie) GetYear() string {
	if m != nil {
		return m.Year
	}
	return ""
}

func (m *Movie) GetUserid() string {
	if m != nil {
		return m.Userid
	}
	return ""
}

func (m *Movie) GetCreatedon() *timestamp.Timestamp {
	if m != nil {
		return m.Createdon
	}
	return nil
}

func (m *Movie) GetUpdatedon() *timestamp.Timestamp {
	if m != nil {
		return m.Updatedon
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_movies_5e83975f200d6708, []int{2}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GetMoviesResponse)(nil), "pb.GetMoviesResponse")
	proto.RegisterType((*Movie)(nil), "pb.Movie")
	proto.RegisterType((*Empty)(nil), "pb.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Movies service

type MoviesClient interface {
	GetMovies(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetMoviesResponse, error)
}

type moviesClient struct {
	cc *grpc.ClientConn
}

func NewMoviesClient(cc *grpc.ClientConn) MoviesClient {
	return &moviesClient{cc}
}

func (c *moviesClient) GetMovies(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetMoviesResponse, error) {
	out := new(GetMoviesResponse)
	err := grpc.Invoke(ctx, "/pb.Movies/GetMovies", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Movies service

type MoviesServer interface {
	GetMovies(context.Context, *Empty) (*GetMoviesResponse, error)
}

func RegisterMoviesServer(s *grpc.Server, srv MoviesServer) {
	s.RegisterService(&_Movies_serviceDesc, srv)
}

func _Movies_GetMovies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoviesServer).GetMovies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Movies/GetMovies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoviesServer).GetMovies(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Movies_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Movies",
	HandlerType: (*MoviesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMovies",
			Handler:    _Movies_GetMovies_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "movies.proto",
}

func init() { proto.RegisterFile("movies.proto", fileDescriptor_movies_5e83975f200d6708) }

var fileDescriptor_movies_5e83975f200d6708 = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0xc1, 0x4e, 0x83, 0x40,
	0x10, 0x86, 0x85, 0x16, 0x2a, 0x53, 0x63, 0x74, 0xa2, 0x66, 0xc3, 0xc5, 0xca, 0x89, 0xd3, 0x92,
	0xe0, 0x45, 0x1f, 0xc0, 0xe8, 0xc5, 0x0b, 0xf1, 0x05, 0xa0, 0x3b, 0x36, 0x9b, 0x94, 0xee, 0x66,
	0x59, 0x4c, 0xfa, 0xc8, 0xbe, 0x85, 0x61, 0xa0, 0x78, 0xf0, 0xe0, 0x6d, 0x66, 0xfe, 0xef, 0xdf,
	0xcd, 0xff, 0xc3, 0x45, 0x6b, 0xbe, 0x34, 0x75, 0xd2, 0x3a, 0xe3, 0x0d, 0x86, 0xb6, 0x49, 0xef,
	0x77, 0xc6, 0xec, 0xf6, 0x54, 0xf0, 0xa5, 0xe9, 0x3f, 0x0b, 0xaf, 0x5b, 0xea, 0x7c, 0xdd, 0xda,
	0x11, 0xca, 0xde, 0xe0, 0xfa, 0x95, 0xfc, 0x3b, 0xfb, 0x2a, 0xea, 0xac, 0x39, 0x74, 0x84, 0x0f,
	0x10, 0x8f, 0x2f, 0x89, 0x60, 0xb3, 0xc8, 0xd7, 0x65, 0x22, 0x6d, 0x23, 0x99, 0xa9, 0x26, 0x01,
	0xaf, 0x60, 0x41, 0xce, 0x89, 0x70, 0x13, 0xe4, 0x49, 0x35, 0x8c, 0xd9, 0x77, 0x00, 0x11, 0x33,
	0x78, 0x09, 0xa1, 0x56, 0x22, 0x60, 0x29, 0xd4, 0x0a, 0x6f, 0x20, 0xf2, 0xda, 0xef, 0x69, 0xa2,
	0xc7, 0x05, 0x53, 0x38, 0x57, 0xda, 0xd1, 0xd6, 0x1b, 0x27, 0x16, 0x2c, 0xcc, 0x3b, 0x22, 0x2c,
	0x8f, 0x54, 0x3b, 0xb1, 0xe4, 0x3b, 0xcf, 0x78, 0x07, 0x71, 0xdf, 0x91, 0xd3, 0x4a, 0x44, 0x7c,
	0x9d, 0x36, 0x7c, 0x82, 0x64, 0xeb, 0xa8, 0xf6, 0xa4, 0xcc, 0x41, 0xc4, 0x9b, 0x20, 0x5f, 0x97,
	0xa9, 0x1c, 0x63, 0xcb, 0x53, 0x6c, 0xf9, 0x71, 0x8a, 0x5d, 0xfd, 0xc2, 0x83, 0xb3, 0xb7, 0x6a,
	0x72, 0xae, 0xfe, 0x77, 0xce, 0x70, 0xb6, 0x82, 0xe8, 0xa5, 0xb5, 0xfe, 0x58, 0x3e, 0x43, 0x3c,
	0x76, 0x87, 0x05, 0x24, 0x73, 0x91, 0xc8, 0x85, 0x31, 0x91, 0xde, 0x0e, 0xe3, 0x9f, 0x8a, 0xb3,
	0xb3, 0x26, 0xe6, 0x2f, 0x1e, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xc1, 0xbd, 0x32, 0x11, 0xb5,
	0x01, 0x00, 0x00,
}
